openapi: 3.0.0
info:
  title: Delilah Restó
  version: 1.0.0
  description: Servicio que gestiona el backend de un restaurante

servers:
  - url: http://localhost:5000
    description: Servidor de desarrollo

paths:
  /users:
    get:
      tags:
        - "users"
      summary: Obtiene una lista de todos los usuarios
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'              
    post:
      tags:
        - "users"
      summary: Crea un nuevo usuario
      operationId: addUser
      parameters:
        - in: body
          required: true
          name: body
          schema:
            $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Ok
        '422':
          description: Datos invalidos
      
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
          example: stejobs20
        fullname:
          type: string
          example: Steve Jobs
        email:
          type: string
          example: steveJobs20@gmail.com
        number:
          type: string
          example: "+5412545410"
        address:
          type: string
          example: LA, USA 1231
        password:
          type: string
          example: "123456"
        
        