name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: sa-east-1 # set this to your preferred AWS region, e.g. us-west-1
  AWS_TAG_NAME: product
  AWS_TAG_VALUE: delilah-resto

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Get instance address
      run: |
        AWS_FILTERS=Name=instance-state-name,Values=running Name=tag:${{ env.AWS_TAG_NAME}},Values=${{ env.AWS_TAG_NAME }}
        AWS_QUERY='Reservations[*].Instances[*].PrivateIpAddress'
        AWS_JSON=$(aws ec2 describe-instances --filters $AWS_FILTERS --query $AWS_QUERY)

        EC2_ADDR=$(echo $AWS_JSON | jq --raw-output 'flatten | join(",")')
        echo $EC2_ADDR
        echo "EC2_ADDRESSES=$EC2_ADDR" >> $GITHUB_ENV
      
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_ADDRESSES }}
        username: ${{ secrets.SSH_USERNAME }}
        sync: true
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: sh deploy.sh
